font_name = "Fira Mono"
font_size = 14
current_theme = "rose-pine-moon"

[theme.catppuccin-latte]
alacritty = "catppuccin-latte"
bat = "catppuccin-latte"
delta = "catppuccin-latte"
fzf = "catppuccin-latte"
ghostty = "Catppuccin Latte"
k9s = "catppuccin-latte"
e1s = "catppuccin_latte"
kitty = "catppuccin-latte"
lazygit = "catppuccin_latte"
nvim = { name = "catppuccin-latte", style = "" }
vivid = "catppuccin-latte"
wezterm = "catppuccin-latte"
zed = "Catppuccin Latte"
zellij = "catppuccin-latte"

[theme.catppuccin-mocha]
alacritty = "catppuccin-mocha"
bat = "catppuccin-mocha"
delta = "catppuccin-mocha"
fzf = "catppuccin-mocha"
ghostty = "Catppuccin Mocha"
k9s = "catppuccin-mocha"
e1s = "catppuccin_mocha"
kitty = "catppuccin-mocha"
lazygit = "catppuccin_mocha"
nvim = { name = "catppuccin-mocha", style = "" }
vivid = "catppuccin-mocha"
wezterm = "catppuccin-mocha"
zed = "Catppuccin Mocha"
zellij = "catppuccin-mocha"

[theme.catppuccin-macchiato]
alacritty = "catppuccin-macchiato"
bat = "catppuccin-macchiato"
delta = "catppuccin-macchiato"
fzf = "catppuccin-macchiato"
ghostty = "Catppuccin Macchiato"
k9s = "catppuccin-macchiato"
e1s = "catppuccin_macchiato"
kitty = "catppuccin-macchiato"
lazygit = "catppuccin_macchiato"
nvim = { name = "catppuccin-macchiato", style = "" }
vivid = "catppuccin-macchiato"
wezterm = "catppuccin-macchiato"
zed = "Catppuccin Macchiato"
zellij = "catppuccin-macchiato"

[theme.rose-pine-moon]
alacritty = "rose-pine-moon"
bat = "rose-pine-moon"
delta = "catppuccin-mocha"
fzf = "rose-pine-moon"
ghostty = "Rose Pine Moon"
k9s = "rose-pine-moon"
e1s = "rose-pine-moon"
kitty = "rose-pine-moon"
lazygit = "tokyonight_moon"
nvim = { name = "rose-pine-moon", style = "" }
vivid = "rose-pine-moon"
wezterm = "rose-pine-moon"
zed = "Rosé Pine Moon"
zellij = "rose-pine-moon"

[theme.rose-pine-dawn]
alacritty = "rose-pine-dawn"
bat = "rose-pine-dawn"
delta = "catppuccin-mocha"
fzf = "rose-pine-dawn"
ghostty = "Rose Pine Dawn"
k9s = "rose-pine-dawn"
e1s = "rose-pine-dawn"
kitty = "rose-pine-dawn"
lazygit = "tokyonight_day"
nvim = { name = "rose-pine-dawn", style = "" }
vivid = "rose-pine-dawn"
wezterm = "rose-pine-dawn"
zed = "Rosé Pine Dawn"
zellij = "rose-pine-dawn"

[theme.tokyonight-moon]
alacritty = "tokyonight-moon"
bat = "tokyonight_moon"
delta = "tokyonight_moon"
fzf = "tokyonight-moon"
ghostty = "TokyoNight Moon"
k9s = "rose-pine"
e1s = "tokyo-night"
kitty = "tokyonight_moon"
lazygit = "tokyonight_moon"
nvim = { name = "tokyonight", style = "moon" }
vivid = "tokyonight-moon"
wezterm = "tokyonight_moon"
zed = "Tokyo Night Storm"
zellij = "tokyonight_moon"

[theme.tokyonight-night]
alacritty = "tokyonight-night"
bat = "tokyonight_night"
delta = "tokyonight-night"
fzf = "tokyonight-night"
ghostty = "TokyoNight Night"
k9s = "stock"
e1s = "tokyo-night"
kitty = "tokyonight_night"
lazygit = "tokyonight_night"
nvim = { name = "tokyonight", style = "night" }
vivid = "tokyonight-night"
wezterm = "tokyonight_night"
zed = "Tokyo Night"
zellij = "tokyonight_night"
