[tools]
usage = "latest"
fnox = "latest"
node = "latest"
bun = "latest"
uv = "latest"
python = "latest"
go = "latest"
java = "corretto-25"
lua = "latest"
zig = "latest"
kubectl = "latest"
krew = "latest"
packer = "latest"
tf-summarize = "latest"
"go:github.com/maaslalani/confetty" = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []

[settings.python]
compile = false
uv_venv_create_args = ["--seed"]

[settings.node]
compile = false

[settings.npm]
bun = true
